          //BANKNIGHT JOB(4242), 'SABRINA BATCH', CLASS=A, MSGCLASS=A
          //STEP01 EXEC PGM=BATCH
          //TRANS DD DSN=SABRINA.BANK.TRANSACT.TXT, DISP=SHR
          //MASTER DD DNS=SABRINA.BANK.MASTER.TXT, DISP=OLD
          //SYSOUT DD SYSOUT=*
